- hosts: localhost
  vars:
      ip: x['instances'][0]['public_ip_address']
  tasks:
  - ec2_instance:
     region: ap-south-1
     image_id: ami-0bcf5425cdc1d8a85
     instance_type: t2.micro
     vpc_subnet_id: subnet-5ffaee37
     security_group: sg-01b91913b5e7046d0
     key_name: aws2020key
     name: osl-lb
     aws_access_key: (Give AWS Access Key)
     aws_secret_key: (Give AWS Secret key)
     state: present
    register: x
  - ec2_instance:
     region: ap-south-1
     image_id: ami-0bcf5425cdc1d8a85
     instance_type: t2.micro
     vpc_subnet_id: subnet-5ffaee37
     security_group: sg-01b91913b5e7046d0
     key_name: aws2020key
     name: os2-ws1
     aws_access_key: (Give AWS Access Key)
     aws_secret_key: (Give AWS Secret key)
     state: present

    register: y
  - ec2_instance:
     region: ap-south-1
     image_id: ami-0bcf5425cdc1d8a85
     instance_type: t2.micro
     vpc_subnet_id: subnet-5ffaee37
     security_group: sg-01b91913b5e7046d0
     key_name: aws2020key
     name: os3-ws2
     aws_access_key: (Give AWS Access Key)
     aws_secret_key: (Give AWS Secret key)
     state: present

    register: z
  - debug:
     var : x
  - debug:
     var: x['instances'][0]['public_ip_address']

  - lineinfile:
     path: "ip.txt"
     insertbefore: [aws_ip_lb]
     line: "{{ x['instances'][0]['public_ip_address'] }} ansible_connection=ssh ansible_user=ec2-user ansible_ssh_private_key_file=/root/aws2020key.pem"
  - blockinfile:
     path: "ip.txt"
     insertafter: [aws_ip_webserver]
     block: |
          {{y['instances'][0]['public_ip_address']}} ansible_connection=ssh ansible_user=ec2-user ansible_ssh_private_key_file=/root/aws2020key.pem
          {{z['instances'][0]['public_ip_address']}} ansible_connection=ssh ansible_user=ec2-user ansible_ssh_private_key_file=/root/aws2020key.pem
  - meta: refresh_inventory
- hosts: aws_ip_lb
  tasks:

  - package:
     name: "haproxy"
     state: present
  - template:
     src: "haproxy1.cfg"
     dest: "/etc/haproxy/haproxy.cfg"
  - service:
     name: "haproxy"
     state: restarted
- hosts: aws_ip_webserver
  tasks:
  - package:
     name: "httpd"
     state: present
  - package:
     name: "php"
     state: present
  - copy:
     src: "task12.php"
     dest: "/var/www/html/index.php"
  - service:
     name: "httpd"
     state: restarted
